function(print_summary)
    message(STATUS "")
    message(STATUS "******** Summary ********")
    message(STATUS "  OS                              : ${CMAKE_SYSTEM_NAME} ${CMAKE_SYSTEM_VERSION}")
    message(STATUS "  CMake version                   : ${CMAKE_VERSION} (${CMAKE_COMMAND})")
    message(STATUS "  Build type                      : ${CMAKE_BUILD_TYPE}")
    message(STATUS "  Build directory                 : ${CMAKE_BINARY_DIR}")
    message(STATUS "  C++ compiler ID                 : ${CMAKE_CXX_COMPILER_ID}")
    message(STATUS "  C++ compiler version            : ${CMAKE_CXX_COMPILER_VERSION} (${CMAKE_CXX_COMPILER})")
    message(STATUS "  C++ flags (all build types)     : ${CMAKE_CXX_FLAGS}")
    if(${CMAKE_BUILD_TYPE} STREQUAL "Debug")
        message(STATUS "  C++ flags (build type 'Debug')  : ${CMAKE_CXX_FLAGS_DEBUG}")
    elseif(${CMAKE_BUILD_TYPE} STREQUAL "Release")
        message(STATUS "  C++ flags (build type 'Release'): ${CMAKE_CXX_FLAGS_RELEASE}")
    else()
        message(FATAL_ERROR "Build type not supported: ${CMAKE_BUILD_TYPE}")
    endif()
    message(STATUS "")
endfunction()
